version: 2
updates:
  - package-ecosystem: "ban"
    directory: "/frontend"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"
